services:
  postgres:
    image: 'postgres:latest'
    environment:
    - 'POSTGRES_DB=form'
    - 'POSTGRES_USER=postgres'
    - 'POSTGRES_PASSWORD=1'
    - 'POSTGRES_HOST_AUTH_METHOD=trust'
    ports:
    - '5433:5432'